# Example parameters file for GHFC WGS Alignment Pipeline
# Copy this file and modify the paths according to your setup

# Pipeline steps control - ALL REQUIRED STEPS MUST BE LISTED
steps: [
    "alignment",
    "deepvariant_sample",
    "deepvariant_family",
    "annotation",
    "snvs_cohort",
    "wisecondorx",
    "wombat",
  ] # Available steps: alignment, deepvariant_sample, deepvariant_family, annotation, snvs_cohort, wisecondorx, wombat

# Input/Output paths
data: "/pasteur/helix/projects/ghfc_wgs/WGS/test-GRCh38/"
scratch: "/pasteur/appa/scratch/fcliquet"

# Cohort name for merged files
cohort_name: "test_cohort"

# Pedigree file (optional - defaults to {data}/pedigree.tsv)
pedigree: "/pasteur/helix/projects/ghfc_wgs/WGS/test-GRCh38/pedigree.tsv"

# Reference genomes
ref: "/pasteur/helix/projects/ghfc_wgs/references/GRCh38/chr/GRCh38.fasta"
ref_name: "GRCh38_GIABv3"
oldref: "/pasteur/helix/projects/ghfc_wgs/references/GRCh38/chr/hs38DH.fa"
wisecondorx_reference: "/pasteur/helix/projects/ghfc_wgs/references/GRCh38/WisecondorX/reference_wisecondorX_hg38_5kb.npz"

# File patterns (adjust according to your naming convention)
fastq_pattern: ""
cram4realignment_pattern: "*.cram"

# Tool paths (when not using containers)
bwa_mem2: "bwa-mem2"
samblaster: "samblaster"
sambamba: "sambamba"
samtools: "samtools"
bazam: "/pasteur/helix/projects/ghfc_wgs/tools/bazam-1.0.1/bazam.jar"

# GLnexus configuration
glnexus_config: "DeepVariant_unfiltered"

# DeepVariant configuration
# WARNING: Update DeepVariant process settings accordingly to the number of threads
deepvariant_threads: 96 # Number of parallel tasks for DeepVariant make_examples

# gnomAD frequency annotation configuration
gnomad_file: "/pasteur/helix/projects/ghfc_wgs/refs/gnomad_v4.1_allChroms.bcf" # Path to gnomAD annotation file
gnomad_filter_field: "AF" # gnomAD field to filter on (e.g., AF, AF_popmax)
gnomad_filter_threshold: "0.01" # Frequency threshold for filtering (e.g., 0.01 for 1%)

# VEP annotation configuration
vep_config: "/pasteur/helix/projects/ghfc_wgs/configs/vep_config.ini" # Path to VEP config INI file
vep_config_name: "ensembl_vep_115" # Name suffix for output files

# Annotation additional annotation configuration
annotation_annotation_path: "/pasteur/appa/scratch/ghfc/scratch-cache/gnomad/" # Directory containing annotation BCF files
annotation_annotation_list: ["gnomad_v4.1_allChroms.bcf"] # List of BCF files for additional annotation

# Annotation de novo mutation extraction configuration
annotation_dnm_min_callrate: "0.9" # Minimum call rate for de novo variants (default: 0.9)
annotation_dnm_min_DP: "10" # Minimum depth (DP) for de novo variants in child (default: 10)
annotation_dnm_min_GQ: "19" # Minimum genotype quality (GQ) for de novo variants in child (default: 20)
annotation_dnm_min_VAF: "0.25" # Minimum variant allele frequency (VAF) for de novo variants in child (default: 0.2)

# Wombat configuration
wombat_config_path: "/pasteur/appa/scratch/ghfc/scratch-cache/pywombat" # Directory containing Wombat YAML configuration files
wombat_config_list: ["dataset_paper.yml"] # List of Wombat config files (e.g., ["config1.yml", "config2.yml"])

# Pseudo-autosomal regions (PAR) coordinates for GRCh38
ref_par1_start: "10001" # PAR1 start position on chrX (GRCh38)
ref_par1_end: "2781479" # PAR1 end position on chrX (GRCh38)
ref_par2_start: "155701383" # PAR2 start position on chrX (GRCh38)
ref_par2_end: "156030895" # PAR2 end position on chrX (GRCh38)

# SLURM account and partition settings
slurm_account: "your_account"
slurm_partition: "ghfc"

# Container cache directory
apptainer_cache: "/pasteur/helix/projects/ghfc_wgs/WGS/test-GRCh38/container-cache/"
singularity_cache: "/pasteur/helix/projects/ghfc_wgs/WGS/test-GRCh38/container-cache/"

# Resource limits
max_memory: "460.GB"
max_cpus: 95
max_time: "240.h"
